repos:
    # built-in pre-commit hooks
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
    -   id: trailing-whitespace
    -   id: end-of-file-fixer
    -   id: check-yaml
    -   id: check-json
    -   id: check-added-large-files

    # black
-   repo: https://github.com/psf/black
    rev: 23.7.0
    hooks:
    -   id: black

    # flake8
-   repo: https://github.com/PyCQA/flake8
    rev: 6.1.0
    hooks:
    -   id: flake8

    # mypy
-   repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.5.1
    hooks:
    -   id: mypy

    # isort
-   repo: https://github.com/PyCQA/isort
    rev: 5.12.0
    hooks:
    -   id: isort
        name: isort (python)

    # local hooks: pylint
-   repo: local
    hooks:
    -   id: pylint
        name: pylint
        entry: pylint src tests
        language: system
        types: [python]
        require_serial: true
